### ISSUE TITLE
Linkedin Messaging is buggy

### ISSUE THREAD

**Issue by hyperwidget** [Unbiasify/unbiasify#3]
Some names show up, some don't - to satisfy this issue we should try to make sure that all names/images do not show up if the correlating toggle is enabled

**Comment by rohannair** [comment]
@hyperwidget I'd love to help but need a bit more on this bug:

- Steps to reproduce
- Expected results
- Actual results
- Any misc. context
- Screenshots

**Comment by hyperwidget** [comment]
@rohannair This was actually in the original .md file that @1hauck had inside the project when I brought it into github; he would be the better source to elaborate
