### ISSUE TITLE
Reduce duplication in styling

### ISSUE THREAD

**Issue by hyperwidget** [Unbiasify/unbiasify#38]
We should look to avoid styling duplication where possible:

A big step toward this would be to extract all the uses of commonly used strings into constants:

For example:

`{ visibility: hidden !important; }` could be extracted into `const HIDE_STYLE = '{ visibility: hidden !important; }'`

Which can then be used, thanks to string interpolation like:

`` `a.u-colorGray3.u-uncoloredLink ${HIDE_STYLE}`,``

**Comment by bhavyata9** [comment]
Good call

**Comment by rohannair** [comment]
Perhaps adding in some CSS build enhancements will help with this. See: #43
