### ISSUE TITLE
Enhancement - Twitter

### ISSUE THREAD

**Issue by hyperwidget** [Unbiasify/unbiasify#4]
We should have the ability to toggle names/images on off on twitter the same way we currently have for linkedin with individual settings

**Comment by bkd705** [comment]
Hey! I'd love to tackle this, but just noting from #2 should I wait until you sort out a better file structure, or is that not in the works anymore?

**Comment by hyperwidget** [comment]
Hey @bkd705!

I think the restructure is probably a little bit and some talking away, so don't wait on our accord!

**Comment by bkd705** [comment]
Sounds good! I'll give this one a go then!

**Comment by bhavyaSA** [comment]
Closing this as @bkd705 addressed it.

**Comment by hyperwidget** [comment]
Right! Thanks :D
