### ISSUE TITLE
enhancements - Dropdown Menu

### ISSUE THREAD

**Issue by 1hauck** [Unbiasify/unbiasify#40]
have a button that lets people easily share on social media
have a button that directs people to additional resources i.e. www.unbiasify.com
have a button that lets people share feedback easily

**Comment by hyperwidget** [comment]
I'm going to break this out into separate issues, since this whole thing is a pretty big hunka work

**Comment by hyperwidget** [comment]
I'm closing this down, as I've broken it out into separate issues #47 #48 and #49
