### ISSUE TITLE
Enhancement - Repl.it classroom

### ISSUE THREAD

**Issue by ShaunLloyd** [Unbiasify/unbiasify#50]
Hi Unbiasify team 👋 

Bridge school is opening up applications for it's next cohort and we're looking to use the new classroom feature in repl.it to give out our coding test for candidates. We wanted to make a chrome extension to hide the names and profile pictures of our applicants for when we review them but wondered if this was something that could be potentially useful for unbiasify too?

If this is something you would be interested in, i would love to put up a pull request to add Repl.it to your extension.

**Comment by hyperwidget** [comment]
We would absolutely love a pr adding repl.it to our ever growing list of networks that we're reducing bias from. 

Bridge school is a fantastic program and we couldn't be happier to have folks from your program contribute t, and find use in, what we're doing

**Comment by ShaunLloyd** [comment]
## Update

I have posted Pull Request #54 that addresses this issue.

**Comment by bhavyaSA** [comment]
Thanks @ShaunLloyd, looks good!
