### ISSUE TITLE
enhancement - Facebook

### ISSUE THREAD

**Issue by hyperwidget** [Unbiasify/unbiasify#6]
We should have the ability to toggle names/images on off on facebook the same way we currently have for linkedin with individual settings

**Comment by turquoisemelon** [comment]
Hi,
This is a really cool project. Is it open to contributors? I would like to work on this issue if it hasn't been taken on by someone else.
Thanks,

**Comment by bhavyaSA** [comment]
@turquoisemelon, yes it definitely is! Would appreciate help on this issue.

**Comment by hyperwidget** [comment]
Hey @turquoisemelon as @bhavyaSA said; absolutely! Your contribution would be fantastically appreciated 👏

**Comment by turquoisemelon** [comment]
Great! I've already started to work on it. The logic was already written for other platforms. All I'm doing is plugging that logic in with the facebook specific settings.

**Comment by hyperwidget** [comment]
That sounds about right :D
