### ISSUE TITLE
Enhancement - Reduce Toggles

### ISSUE THREAD

**Issue by hyperwidget** [Unbiasify/unbiasify#63]
We've decided that it's best for user experience to collapse both photo toggles and name toggles under a single toggle per social network - as @1hauck says: `it’s like saying you only want to be half racist`

This means that for each network there should only be one toggle to enable obfuscation across names and photos.

Acceptance for this ticket does _not_ require any alteration to the obfuscation logic - we can simply have the single toggle call both toggle actions for now.

**Comment by Aditya-Kolla** [comment]
I'll try.

**Comment by hyperwidget** [comment]
🎉thanks!

**Comment by Aditya-Kolla** [comment]
Is this comment section a good place to talk? Because the plugin just won't work on my computer. I tried turning it on multiple times but it won't hide the photos and names.
