### ISSUE TITLE
Master Toggles

### ISSUE THREAD

**Issue by hyperwidget** [Unbiasify/unbiasify#9]
It would be great to have the ability to toggle names off for all supported sites

In the same vein, we should also cover the same for images

While we're at it, let's also have the same to toggle both images and names on/off

**Comment by bhavyaSA** [comment]
Do we still need this with the shortcut?

**Comment by hyperwidget** [comment]
Actually, probably not
BUT, we should document somewhere the key commands for users

**Comment by bhavyata9** [comment]
Added in README
